/*
  ULTRASPACE CONTENT FILE
  -----------------------
  Replace any profile image by setting `image` to a relative path, for example:
  image: "./assets/patchwork.png"

  Majors come from the DLS Majors sheet. Anything not on that sheet (songs,
  usernames, blurbs for the newer profiles) is placeholder voice, not canon.
*/

window.ULTRASPACE_DATA = {
  characters: [
    {
      id: "patchwork",
      name: "Aaliyah",
      username: "patchwork.exe",
      initials: "AM",
      theme: "patchwork",
      image: "",
      quote: "yeah, I coded it myself.",
      details: ["U.A. University", "Sociology + Computer Science (double major)", "somewhere near the computer lab"],
      lastLogin: "09/08/2006",
      mood: "secretive ♡",
      status: "rewriting my layout. again.",
      online: true,
      song: "Dirty Little Secret — The All-American Rejects",
      about: "I like code that works, clothes that don’t look like they were selected in the dark, and people who can keep a secret. Two of those things are easier to find than the third. If the page looks broken on your computer, that sounds personal.",
      meet: "Nobody. I already know too many people. (Exceptions may apply.)",
      interests: {
        General: "HTML, CSS, late-night coding, pretty interfaces, gossip I did not technically ask to hear, making playlists for extremely specific moods.",
        Music: "Pop-punk, R&B, dance tracks, songs that become suspicious when placed on a profile.",
        Movies: "Anything stylish, dramatic, or fun enough to quote afterward.",
        Heroes: "People who mind their business. So, very few of you."
      },
      top8: ["tamaki", "jirou", "ochaco", "izuku", "momo", "kirishima", "nejire", "mirio"],
      blogs: [
        ["09/08", "CSS is not a personality trait", "unless you are better at it than everybody else."],
        ["09/03", "hypothetically", "If two people know their friends are each seeing somebody, there is no reason to assume those somebodies are the same person." ]
      ],
      comments: [
        ["jirou", "your autoplay nearly killed me. turn it down."],
        ["izuku", "The navigation update looks really good! I wrote down a few accessibility notes if you want them—"],
        ["tamaki", "you said you were going to sleep three hours ago"],
        ["patchwork", "@tamaki and you said you weren't checking my profile ♡"]
      ]
    },
    {
      id: "tamaki",
      name: "Tamaki Amajiki",
      username: "suneater",
      initials: "TA",
      theme: "tamaki",
      image: "",
      quote: "please don't forward my profile to anyone",
      details: ["U.A. University", "Environmental Science / Biology (leaning Marine Biology)", "probably offline"],
      lastLogin: "09/08/2006",
      mood: "tired",
      status: "away",
      online: false,
      song: "profile song hidden",
      about: "There isn’t much to say. Mirio made the account. Nejire picked the username. Someone else changed the colors.",
      meet: "I think I have met enough people.",
      interests: {
        General: "Quiet places, food, not being perceived, the people already in my life.",
        Music: "Whatever is already playing.",
        Movies: "I don’t watch many.",
        Heroes: "Mirio. Nejire."
      },
      top8: ["mirio", "nejire", "patchwork", "kirishima", "izuku", "ochaco", "momo", "jirou"],
      top8History: [
        { date: "09/08/2006", top8: ["mirio", "nejire", "patchwork", "kirishima", "izuku", "ochaco", "momo", "jirou"], note: "Mirio is #1, Nejire is #2 and Aaliyah is #3. Aaliyah treats this as proof that Tamaki secretly wants Mirio and that she is, at best, his side girlfriend. She isn’t seriously jealous. She just found a joke that makes him malfunction." }
      ],
      blogs: [["08/29", "first post", "I was told the empty page looked suspicious."]],
      comments: [
        ["mirio", "THERE HE IS!!! welcome to UltraSpace!!"],
        ["nejire", "I still think we should put the sparkly bats back"],
        ["patchwork", "your layout is fine. don't let them touch it."]
      ]
    },
    {
      id: "izuku",
      name: "Izuku Midoriya",
      username: "quirknotes",
      initials: "IM",
      theme: "izuku",
      image: "",
      quote: "sorry about the long About Me section!",
      details: ["U.A. University", "Kinesiology / Exercise Science (pre-Physical Therapy)", "usually in the library"],
      lastLogin: "09/08/2006",
      mood: "focused",
      status: "working on a post (draft 14)",
      online: true,
      song: "The Middle — Jimmy Eat World",
      about: "Hi! I’m Izuku. This profile is mostly for friends, class notes, hero analysis, event photos, and short blog updates. The blog updates are sometimes not short. I’m still organizing the links on the left, so please tell me if anything goes to the wrong page.",
      meet: "People who care deeply about what they do. Also anyone willing to compare notes after lecture.",
      interests: {
        General: "Analysis notebooks, campus events, training plans, collecting articles, helping friends study.",
        Music: "Upbeat study playlists and whatever my friends send me.",
        Movies: "Hero documentaries, action movies, anything with a good character arc.",
        Heroes: "Too many to fit in this box. I tried."
      },
      top8: ["shoto", "patchwork", "ochaco", "kirishima", "bakugo", "momo", "jirou", "kaminari"],
      blogs: [["09/07", "A quick note about yesterday’s seminar", "This post is 2,843 words. That is still quick compared with the first draft."]],
      comments: [["shoto", "I read the whole post."], ["patchwork", "of course you did, shoto"]]
    },
    {
      id: "shoto",
      name: "Shoto Todoroki",
      username: "shoto",
      initials: "ST",
      theme: "shoto",
      image: "",
      quote: "I was told this is required.",
      details: ["U.A. University", "Economics", "on campus"],
      lastLogin: "09/07/2006",
      mood: "fine",
      status: "reading Izuku’s new post",
      online: false,
      song: "No song selected",
      about: "My name is Shoto. I attend U.A. University. There are additional fields below.",
      meet: "People who are thoughtful, determined, kind, observant, intelligent, and sometimes mutter while taking notes.",
      interests: { General: "Cold soba, quiet study spaces, spending time with friends.", Music: "No preference.", Movies: "No preference.", Heroes: "Not answering this publicly." },
      top8: ["izuku", "momo", "patchwork", "ochaco", "kirishima", "bakugo", "jirou", "kaminari"],
      blogs: [["09/01", "Title", "Izuku said the blog did not work until I published something."]],
      comments: [["momo", "Your page is very… efficient."], ["izuku", "I can help you add a background if you want!"]]
    },
    {
      id: "bakugo",
      name: "Katsuki Bakugo",
      username: "groundzero",
      initials: "KB",
      theme: "bakugo",
      image: "",
      quote: "WHY ARE YOU ON MY PAGE",
      details: ["U.A. University", "Chemical Engineering", "none of your business"],
      lastLogin: "09/08/2006",
      mood: "annoyed",
      status: "do not IM me",
      online: true,
      song: "Know Your Enemy — Green Day",
      about: "If you know me, you already know. If you don’t, leave.",
      meet: "Nobody.",
      interests: { General: "Training, cooking, winning.", Music: "Loud.", Movies: "The ones where people stop talking and do something.", Heroes: "Not doing this." },
      top8: ["kirishima"],
      top8History: [
        { date: "09/08/2006", top8: ["kirishima"], note: "Kirishima is the only person in the Top 8. The other seven slots are empty. Bakugo says this means nothing because “he’s my friend.” He clearly knows exactly how to customize his page." }
      ],
      blogs: [["09/06", "STOP COMMENTING", "I know how to turn comments off."]],
      comments: [["kirishima", "BRO THE NEW SONG IS SICK"], ["kaminari", "hey man why am i not in your top 8"], ["sero", "you have eight slots and you used one"], ["bakugo", "HE’S MY FRIEND"]]
    },
    {
      id: "kirishima",
      name: "Eijiro Kirishima",
      username: "redriotrocks",
      initials: "EK",
      theme: "kirishima",
      image: "",
      quote: "LIVE BRAVE!!!",
      details: ["U.A. University", "Exercise Science / Athletic Training", "gym / wherever the food is"],
      lastLogin: "09/08/2006",
      mood: "PUMPED",
      status: "best week ever probably",
      online: true,
      song: "The Anthem — Good Charlotte",
      about: "What’s up!! I’m Kirishima. I’m here for friends, training, good music, and people who aren’t afraid to be honest about who they are. Ignore anybody saying I spent four hours picking the Top 8 order.",
      meet: "People with guts. People who push themselves. People who are incredibly strong and talented and—this question is weird.",
      interests: { General: "Training, hiking, food, hanging out, action movies.", Music: "Rock, punk, anything good for the gym.", Movies: "Action and horror.", Heroes: "Crimson Riot." },
      top8: ["bakugo", "mina", "kaminari", "sero", "patchwork", "izuku", "ochaco", "ojiro"],
      blogs: [["09/06", "TOP FRIENDS UPDATED", "No reason! Just felt like it!!"]],
      comments: [["kaminari", "subtle bro"], ["sero", "extremely natural and casual ranking"], ["kirishima", "what does that mean"]]
    },
    {
      id: "ochaco",
      name: "Ochaco Uraraka",
      username: "uravitygirl",
      initials: "OU",
      theme: "ochaco",
      image: "",
      quote: "leave something nice before you go! ♡",
      details: ["U.A. University", "Architecture (Civil Engineering was the runner-up)", "dorms"],
      lastLogin: "09/08/2006",
      mood: "hopeful",
      status: "studying!! mostly!!",
      online: true,
      song: "Suddenly I See — KT Tunstall",
      about: "Hi!! I’m Ochaco. I’m trying to keep this page cute and organized, which is difficult because everybody keeps sending me more glitter graphics. I like meeting people, trying new food, and pretending my planner is under control.",
      meet: "Kind people. Honest people. People who are trying, even when trying gets complicated.",
      interests: { General: "Friends, campus festivals, saving money, cute stationery.", Music: "Pop and happy study music.", Movies: "Rom-coms and space movies.", Heroes: "My parents." },
      top8: ["patchwork", "izuku", "toga", "momo", "jirou", "kaminari", "sero", "shoto"],
      blogs: [["09/05", "new semester!!", "We are all going to make good choices this year. Don’t laugh."]],
      comments: [["toga", "your new picture is so cute I could die ♡"], ["patchwork", "ochaco blink twice if you need me"]]
    },
    {
      id: "toga",
      name: "Himiko Toga",
      username: "lovemeplease",
      initials: "HT",
      theme: "toga",
      image: "",
      quote: "if i love you, you'll know ♡",
      details: ["location hidden", "Nursing (initially) → Undeclared", "online somewhere"],
      lastLogin: "09/08/2006",
      mood: "in love",
      status: "thinking about her",
      online: true,
      song: "Tear You Apart — She Wants Revenge",
      about: "I like cute things and honest feelings and people who look beautiful when they’re trying not to be afraid. Don’t send a friend request if you’re boring. Don’t block me either. That’s rude.",
      meet: "You already know who. She knows too.",
      interests: { General: "Love, transformation, collecting cute things, people watching.", Music: "Love songs. Scary love songs. Same thing.", Movies: "Anything romantic.", Heroes: "Ochaco ♡" },
      top8: ["ochaco", "patchwork", "izuku", "jirou", "momo", "kaminari", "sero", "shoto"],
      blogs: [["09/08", "♡♡♡", "Some people look even cuter when they’re worried about you."]],
      comments: [["ochaco", "Can you please text me instead of posting things like this publicly?"], ["toga", "but you read it ♡"]]
    },
    {
      id: "momo",
      name: "Momo Yaoyorozu",
      username: "creati",
      initials: "MY",
      theme: "momo",
      image: "",
      quote: "Please excuse the unfinished reading list.",
      details: ["U.A. University", "Biomedical Engineering", "campus housing"],
      lastLogin: "09/07/2006",
      mood: "productive",
      status: "office hours, then rehearsal",
      online: false,
      song: "Fidelity — Regina Spektor",
      about: "Welcome. I created this page to keep in contact with classmates and organize links to useful campus resources. It has since become considerably less formal than intended.",
      meet: "Thoughtful people with unusual perspectives. Musicians, perhaps.",
      interests: { General: "Reading, planning, study groups, tea, music appreciation.", Music: "Classical, jazz, and several recommendations from Jirou.", Movies: "Historical dramas.", Heroes: "Women who lead with integrity." },
      top8: ["jirou", "shoto", "patchwork", "ochaco", "izuku", "kaminari", "sero", "kirishima"],
      blogs: [["09/04", "A recommended-reading page", "I have been informed that forty-two links may be excessive."]],
      comments: [["jirou", "the song choice is good. don't overthink it."], ["momo", "I was not overthinking it."]]
    },
    {
      id: "jirou",
      name: "Kyoka Jirou",
      username: "stereoheart",
      initials: "KJ",
      theme: "jirou",
      image: "",
      quote: "turn your speakers down first.",
      details: ["U.A. University", "Audio Engineering / Music Production", "Aaliyah’s side of the room"],
      lastLogin: "09/08/2006",
      mood: "unimpressed",
      status: "making a better playlist",
      online: true,
      song: "Maps — Yeah Yeah Yeahs",
      about: "Music. Shows. Friends. If you comment asking what I’m listening to while the player is directly above this box, I’m deleting it.",
      meet: "People with actual taste. This is apparently rarer than it sounds.",
      interests: { General: "Guitar, live shows, record stores, complaining recreationally.", Music: "Alternative, punk, indie, anything honest.", Movies: "Concert films and horror.", Heroes: "My parents." },
      top8: ["patchwork", "momo", "kaminari", "sero", "ochaco", "izuku", "shoto", "kirishima"],
      blogs: [["09/08", "playlist update", "No, the track order is not about anybody."]],
      comments: [["kaminari", "track 3 is about me right"], ["momo", "I particularly liked track six."], ["jirou", "both of you stop"]]
    },
    {
      id: "kaminari",
      name: "Denki Kaminari",
      username: "chargebolt69",
      initials: "DK",
      theme: "kaminari",
      image: "",
      quote: "WELCOME 2 THE ELECTRIC ZONE",
      details: ["U.A. University", "Electrical Engineering", "probably Sero’s room"],
      lastLogin: "RIGHT NOW",
      mood: "⚡ charged ⚡",
      status: "who changed my cursor",
      online: true,
      song: "I Write Sins Not Tragedies — Panic! at the Disco",
      about: "Denki. Student. Future legend. Current owner of the sickest page on UltraSpace. Ignore the three broken images, the host is down and they’ll be back soon probably.",
      meet: "Bands, cool people, anyone who knows how to fix marquees.",
      interests: { General: "Games, music, parties, making playlists, not studying.", Music: "YES.", Movies: "Anything with explosions.", Heroes: "Whoever invented instant messaging." },
      top8: ["sero", "jirou", "kirishima", "bakugo", "patchwork", "momo", "izuku", "ochaco"],
      blogs: [["09/08", "IMPORTANT", "Does anybody know why my visitor counter reset??"]],
      comments: [["sero", "because you pasted over the script"], ["kaminari", "okay but who let me do that"]]
    },
    {
      id: "sero",
      name: "Hanta Sero",
      username: "cellophane",
      initials: "HS",
      theme: "sero",
      image: "",
      quote: "leave a comment or don't, i'm not your dad",
      details: ["U.A. University", "Graphic Design / Visual Communication", "wherever the couch is"],
      lastLogin: "09/08/2006",
      mood: "chill",
      status: "uploading photos",
      online: true,
      song: "Float On — Modest Mouse",
      about: "Mostly photos, music, and proof my friends should not be allowed to customize websites without supervision.",
      meet: "People who can take a joke. People with snacks.",
      interests: { General: "Skating, photography, hanging out, making fun of Denki’s layout.", Music: "Indie, hip-hop, whatever sounds good.", Movies: "Comedies.", Heroes: "My friends when they’re buying food." },
      top8: ["kaminari", "kirishima", "bakugo", "jirou", "patchwork", "momo", "izuku", "ochaco"],
      blogs: [["09/07", "photo dump", "If you hate your picture, you should have noticed the camera."]],
      comments: [["kaminari", "DELETE THE THIRD PHOTO"], ["sero", "no ♡"]]
    },
    {
      id: "mirio",
      name: "Mirio Togata",
      username: "lemillion",
      initials: "MT",
      theme: "mirio",
      image: "",
      quote: "HEY!!! GLAD YOU’RE HERE!!!",
      details: ["U.A. University", "Education (Elementary, with a Special Education component)", "all over campus"],
      lastLogin: "09/08/2006",
      mood: "GREAT",
      status: "come say hi!",
      online: true,
      song: "Walking on Sunshine — Katrina and the Waves",
      about: "Mirio! I like meeting people, helping where I can, and making sure Tamaki checks his messages at least once a week.",
      meet: "Everybody! Seriously!",
      interests: { General: "Friends, training, volunteering, terrible jokes.", Music: "Anything upbeat.", Movies: "Comedies and action.", Heroes: "People who keep going." },
      top8: ["tamaki", "nejire", "patchwork", "izuku", "kirishima", "momo", "ochaco", "jirou"],
      blogs: [["09/08", "GOOD MORNING", "This is your reminder that today can still be great!"]],
      comments: [["tamaki", "it is 6:12 in the morning"], ["nejire", "GOOD MORNING!!!!"]]
    },
    {
      id: "nejire",
      name: "Nejire Hado",
      username: "spiralgal",
      initials: "NH",
      theme: "nejire",
      image: "",
      quote: "ask me something!!! anything!!!",
      details: ["U.A. University", "Journalism / Communications", "currently everywhere"],
      lastLogin: "09/08/2006",
      mood: "curious",
      status: "taking another personality quiz",
      online: true,
      song: "Everywhere — Michelle Branch",
      about: "Hi!! Do you like the stars? Should there be more stars? I had more but Tamaki said they made the text hard to read. What classes are you taking? What’s your favorite color? Do you think profile colors say something about a person?",
      meet: "Everyone interesting, which might be everyone.",
      interests: { General: "Questions, fashion, science, people, quiz results.", Music: "Everything sparkly.", Movies: "Fantasy and documentaries.", Heroes: "My friends." },
      top8: ["tamaki", "mirio", "patchwork", "momo", "ochaco", "jirou", "izuku", "kirishima"],
      blogs: [["09/08", "QUIZ RESULT", "I am apparently 82% moon fairy. What are you?"]],
      comments: [["mirio", "I got 40% golden retriever!"], ["tamaki", "how is that an option"]]
    },
    {
      id: "tomura",
      name: "Tomura Shigaraki",
      username: "player_two",
      initials: "TS",
      theme: "tomura",
      image: "",
      quote: "connection timed out",
      details: ["U.A. University", "Computer Science (technically strong, chronically near academic probation)", "computer lab after hours"],
      lastLogin: "09/08/2006 03:41 AM",
      mood: "irritated",
      status: "your code is bad",
      online: false,
      song: "no media detected",
      about: "This account exists because certain group pages are not visible without one. Do not add me unless we share a class or a server.",
      meet: "Competent people. The search continues.",
      interests: { General: "Games, systems, code review nobody requested.", Music: "Background noise.", Movies: "Bad endings.", Heroes: "404 NOT FOUND" },
      top8: ["patchwork", "izuku", "kaminari", "sero", "jirou", "momo", "shoto", "bakugo"],
      blogs: [["09/08", "css specificity", "If you need !important six times, start over."]],
      comments: [["patchwork", "you use tables for layout."], ["tomura", "IT IS 2006"]]
    },
    {
      id: "iida",
      name: "Tenya Iida",
      username: "ingenium_t",
      initials: "TI",
      theme: "iida",
      image: "",
      quote: "please observe all posted guidelines.",
      details: ["U.A. University", "Political Science / Public Administration (pre-law)", "student government office"],
      lastLogin: "09/08/2006",
      mood: "diligent",
      status: "drafting a proposal about profile autoplay",
      online: true,
      song: "Time Is Running Out — Muse",
      about: "Hello. I am Tenya Iida. This profile complies with all posted community guidelines, which I have read twice. I joined to stay in contact with classmates, post student-government announcements, and monitor several concerning trends in profile music.",
      meet: "Responsible people. Classmates who answer their email. Anyone willing to attend a meeting before 9 AM.",
      interests: { General: "Student government, running, debate, public policy, punctuality.", Music: "Whatever keeps a steady tempo.", Movies: "Courtroom dramas and documentaries.", Heroes: "My older brother." },
      top8: ["izuku", "ochaco", "momo", "shoto", "tsuyu", "kirishima", "bakugo", "mina"],
      blogs: [["09/07", "Regarding profile music autoplay", "Several profiles begin playing audio without warning. This is a public-safety concern and I will be raising it."]],
      comments: [["jirou", "you wrote four paragraphs about my autoplay."], ["iida", "It was a measured response."], ["izuku", "Iida, I think it was a good proposal! Maybe just one paragraph shorter?"]]
    },
    {
      id: "mina",
      name: "Mina Ashido",
      username: "acidqueen",
      initials: "MA",
      theme: "mina",
      image: "",
      quote: "dance like nobody is checking your Top 8",
      details: ["U.A. University", "Fashion Merchandising / Marketing", "wherever the party is"],
      lastLogin: "09/08/2006",
      mood: "sparkly",
      status: "planning Friday night (details TBD)",
      online: true,
      song: "Hung Up — Madonna",
      about: "Hiii!! I like dancing, shopping, matching outfits, and knowing literally everything about everybody. Please do not ask how I know. Marketing major so I am basically professionally obligated to have opinions about your layout.",
      meet: "Anyone who can dance. Anyone who cannot but will try anyway. Boys and girls with great jackets.",
      interests: { General: "Dancing, fashion, window shopping, planning group outings, being right about people.", Music: "Pop, dance, and anything with a beat drop.", Movies: "Rom-coms and musicals.", Heroes: "Every girl who ever walked into a room like she owned it." },
      top8: ["kirishima", "star", "patchwork", "jirou", "tsuyu", "hagakure", "ochaco", "aoyama"],
      blogs: [["09/08", "FRIDAY", "Everyone wear something that makes me jealous. That is the whole dress code."]],
      comments: [["kaminari", "i am bringing the speakers"], ["mina", "you are NOT"], ["sero", "he is bringing the speakers"], ["kirishima", "MINA WE ARE GETTING FOOD AFTER THIS"]]
    },
    {
      id: "tsuyu",
      name: "Tsuyu Asui",
      username: "ribbitribbit",
      initials: "AT",
      theme: "tsuyu",
      image: "",
      quote: "if you have something on your mind, ribbit it out",
      details: ["U.A. University", "Environmental Science / Ecology (leaning Aquatic Ecology)", "the pond behind the science building"],
      lastLogin: "09/08/2006",
      mood: "calm",
      status: "taking field notes",
      online: true,
      song: "Rainy Days and Mondays — Carpenters",
      about: "I am Tsuyu. Please call me Tsu. I like rain, ponds, honest people, and saying what I am thinking right when I am thinking it. It saves time.",
      meet: "People who are nice to everybody, not only to the people they like.",
      interests: { General: "Fieldwork, swimming, water-quality sampling, my younger siblings, rainy days.", Music: "Quiet, steady, whatever fits the weather.", Movies: "Nature documentaries.", Heroes: "My little brother and sister." },
      top8: ["ochaco", "mina", "tamaki", "hagakure", "momo", "izuku", "jirou", "shoto"],
      blogs: [["09/06", "Rain log", "Rained for eleven hours. Best day of the semester."]],
      comments: [["ochaco", "you wrote that you were happy and then listed three frogs"], ["tsuyu", "they were all doing well, kero"]]
    },
    {
      id: "hagakure",
      name: "Toru Hagakure",
      username: "invisigirl",
      initials: "TH",
      theme: "hagakure",
      image: "",
      quote: "I’m right here!!",
      details: ["U.A. University", "Hospitality & Event Management", "banquet hall B (setting up)"],
      lastLogin: "09/08/2006",
      mood: "excited",
      status: "planning an event for 40 people",
      online: true,
      song: "Since U Been Gone — Kelly Clarkson",
      about: "HI!! I do events! Parties, mixers, club nights, birthdays. If there is a table and a theme, I want to help. Fun fact: yes, you can see me in the photos. People forget I’m in the room anyway. I think it’s hilarious. I’m quiet until you talk to me, and then I’m a LOT.",
      meet: "Everyone! Especially people who say they hate parties. I will change your mind.",
      interests: { General: "Event planning, decorating, snacks, group chats, matching table runners.", Music: "Anything good for a mixer.", Movies: "Rom-coms and reality shows.", Heroes: "Whoever invented the party planner." },
      top8: ["mina", "ochaco", "tsuyu", "jirou", "kaminari", "sero", "momo", "mirio"],
      blogs: [["09/07", "I MADE A SEATING CHART", "Nobody asked me to. I did it anyway. It is beautiful."]],
      comments: [["mina", "the seating chart is a work of art"], ["hagakure", "THANK YOU I WORKED SO HARD"]]
    },
    {
      id: "tokoyami",
      name: "Fumikage Tokoyami",
      username: "dark_shadow",
      initials: "FT",
      theme: "tokoyami",
      image: "",
      quote: "the night does not apologize for being long",
      details: ["U.A. University", "English Literature (minor in Philosophy)", "the quiet floor of the library"],
      lastLogin: "09/08/2006",
      mood: "pensive",
      status: "reading something I will not summarize",
      online: false,
      song: "The Sound of Silence — Disturbed",
      about: "My name is Fumikage Tokoyami. I read, I write, and I think about endings. The page is dark because the page should be dark. Any glow comes from my friends, who have been told not to touch it. If you are going somewhere, I shall accompany you. If music is required, I shall provide it.",
      meet: "People who read slowly. People who can sit in silence with someone and consider it a good conversation.",
      interests: { General: "Poetry, gothic novels, ethics seminars, long walks at night, tea.", Music: "Dark, atmospheric, preferably with a cello.", Movies: "Gothic horror and film noir.", Heroes: "The authors whose work has outlived them." },
      top8: ["shoto", "izuku", "kaminari", "sero", "jirou", "momo", "mina", "tsuyu"],
      blogs: [["09/05", "On endings", "A book is finished the moment the reader decides it is. The rest is paperwork."]],
      comments: [["kaminari", "bro your page is so cool"], ["tokoyami", "Thank you. Please do not add glitter."], ["kaminari", "too late"]]
    },
    {
      id: "ojiro",
      name: "Mashirao Ojiro",
      username: "tailkick",
      initials: "MO",
      theme: "ojiro",
      image: "",
      quote: "hard work first, snacks after",
      details: ["U.A. University", "Sports Management (with martial-arts coaching)", "the dojo / the gym"],
      lastLogin: "09/08/2006",
      mood: "focused",
      status: "teaching the 6 AM class",
      online: true,
      song: "Seven Nation Army — The White Stripes",
      about: "Hi, I’m Ojiro. I study sports management and teach martial arts on the side. I like practice, routine, and people who show up when they said they would. I am told I am “steady,” which sounds like a compliment.",
      meet: "People who train, coach, or want to learn. Also anybody who can recommend a good ramen place.",
      interests: { General: "Martial arts, coaching, early mornings, meal prep, learning from losses.", Music: "Classic rock and training mixes.", Movies: "Martial-arts movies and sports dramas.", Heroes: "My first instructor." },
      top8: ["kirishima", "sato", "shoji", "koda", "sero", "kaminari", "izuku", "shoto"],
      blogs: [["09/06", "Why I teach", "Everyone who walks in is nervous. That’s fine. We start from there."]],
      comments: [["kirishima", "you taught me the stance and it changed my life"], ["ojiro", "you were the one who practiced for six hours"]]
    },
    {
      id: "shoji",
      name: "Mezo Shoji",
      username: "sixarms",
      initials: "MS",
      theme: "shoji",
      image: "",
      quote: "listening carefully. always.",
      details: ["U.A. University", "Nursing", "nursing lab / clinical placements"],
      lastLogin: "09/08/2006",
      mood: "steady",
      status: "finishing clinical hours",
      online: false,
      song: "Mad World — Gary Jules",
      about: "I’m Shoji. I’m studying nursing. I notice more than I mention, and I prefer it that way. If you need something, ask. I will probably already have noticed.",
      meet: "People who are kind when no one is watching. Patients who actually take their medication.",
      interests: { General: "Nursing, cooking for friends, quiet study rooms, watching people who need help before they ask.", Music: "Soft instrumentals.", Movies: "Medical dramas, but only to critique them.", Heroes: "Nurses everywhere." },
      top8: ["tokoyami", "koda", "ojiro", "sato", "tsuyu", "izuku", "shoto", "momo"],
      blogs: [["09/04", "Clinical hours", "Today I learned that a calm voice is a medical tool."]],
      comments: [["koda", "thank you for checking on me yesterday"], ["shoji", "Of course."]]
    },
    {
      id: "koda",
      name: "Koji Koda",
      username: "animalwhisper",
      initials: "KK",
      theme: "koda",
      image: "",
      quote: "(he’s a bit shy, but he likes you)",
      details: ["U.A. University", "Wildlife Biology / Zoology", "the campus arboretum"],
      lastLogin: "09/07/2006",
      mood: "peaceful",
      status: "feeding the squirrels (against policy)",
      online: false,
      song: "The Reason — Hoobastank",
      about: "Hello. I’m Koji. I like animals, plants, and quiet places. My friends say I should write more about myself, but I think the squirrels are more interesting.",
      meet: "Gentle people. People who are kind to animals and to anyone who is nervous.",
      interests: { General: "Birdwatching, hiking, field sketching, the arboretum.", Music: "Ambient and nature recordings.", Movies: "Wildlife documentaries.", Heroes: "The people who work at wildlife rescues." },
      top8: ["shoji", "tokoyami", "ojiro", "tsuyu", "sato", "mina", "izuku", "ochaco"],
      blogs: [["09/03", "New bird", "A small brown one. Very small. I will not say which."]],
      comments: [["tsuyu", "it was a wren, kero"], ["koda", "I know. I wanted to keep it private."]]
    },
    {
      id: "sato",
      name: "Rikido Sato",
      username: "sugarrush",
      initials: "RS",
      theme: "sato",
      image: "",
      quote: "everything tastes better shared",
      details: ["U.A. University", "Hospitality Management / Culinary Arts", "the campus kitchen"],
      lastLogin: "09/08/2006",
      mood: "content",
      status: "testing a new recipe (extra batter)",
      online: true,
      song: "Good Life — Kanye West",
      about: "Hi, I’m Rikido. I bake, I cook, and I run a very casual dinner night in the dorm kitchen. If you show up hungry, you leave less hungry. That is the whole system.",
      meet: "Anyone who likes food. Anyone who says they “don’t really eat” and then eats three helpings.",
      interests: { General: "Baking, meal planning, running dinner night, strength training, sugar.", Music: "Anything good to cook to.", Movies: "Cooking competitions.", Heroes: "My grandmother, who taught me everything." },
      top8: ["kirishima", "ojiro", "sero", "kaminari", "shoji", "mina", "momo", "izuku"],
      blogs: [["09/05", "Dinner night rules", "Rule one: bring a friend. Rule two: wash a dish. There is no rule three because everyone ignores it."]],
      comments: [["kaminari", "your brownies are illegal"], ["sato", "they’re just brownies"]]
    },
    {
      id: "mineta",
      name: "Minoru Mineta",
      username: "grapejuice",
      initials: "MM",
      theme: "mineta",
      image: "",
      quote: "buy low, sell high, call me anytime",
      details: ["U.A. University", "Business / Marketing", "the student-entrepreneur lounge"],
      lastLogin: "09/08/2006",
      mood: "scheming (for profit)",
      status: "launching a very small business (more soon)",
      online: true,
      song: "Money — Pink Floyd (he picked it ironically)",
      about: "Hey. Minoru. I’m in business and I’m going to be rich, probably before graduation. Please do not ask about the pitch deck, it’s for investors. (I do not have investors yet.)",
      meet: "Business majors. Girls who need a business major. Anyone with a startup idea who needs a co-founder. (Not weird. Business.)",
      interests: { General: "Business plans, small ventures, flipping sneakers, networking events, selling things.", Music: "Hustle playlists.", Movies: "Business movies with great montages.", Heroes: "My mentor, who is an actual millionaire. Probably." },
      top8: ["kaminari", "sero", "aoyama", "sato", "kirishima", "bakugo", "izuku", "momo"],
      blogs: [["09/01", "Why I’m going to be rich", "Step one: a clear plan. Step two: a clear plan. Step three: I haven’t written that one yet."]],
      comments: [["kaminari", "your “investors” are my cousins"], ["mineta", "they have disposable income"]]
    },
    {
      id: "aoyama",
      name: "Yuga Aoyama",
      username: "sparkle_yuga",
      initials: "YA",
      theme: "aoyama",
      image: "",
      quote: "mon dieu, you’re early. the sparkle was not ready.",
      details: ["U.A. University", "Fashion Design", "the design studio (3 a.m.)"],
      lastLogin: "09/08/2006",
      mood: "dazzling",
      status: "hand-beading a sleeve",
      online: true,
      song: "Material Girl — Madonna",
      about: "Bonjour. I am Yuga Aoyama. I design clothing and I believe every outfit deserves a story. My page is as simple as I could make it. (It is not simple.)",
      meet: "People with style. People who want style. People who have never been told they have style.",
      interests: { General: "Fashion design, drawing, beading, tailoring, fabric stores, sparkle.", Music: "Dramatic pop and dance.", Movies: "Costume dramas and runway documentaries.", Heroes: "Every designer who started in a basement." },
      top8: ["mina", "hagakure", "ochaco", "momo", "jirou", "sero", "tokoyami", "mineta"],
      blogs: [["09/06", "Sleeve 4", "If the light hits it properly, a sleeve can change a person’s whole week."]],
      comments: [["mina", "the sleeve is perfect"], ["aoyama", "Merci. It took 19 hours."]]
    },
    {
      id: "touya",
      name: "Touya Todoroki",
      username: "burnout",
      initials: "TT",
      theme: "touya",
      image: "",
      quote: "the page is still here. so am I.",
      details: ["U.A. University", "Communications → Undeclared (after multiple major changes)", "somewhere off campus"],
      lastLogin: "06/14/2006",
      mood: "tired",
      status: "still deciding",
      online: false,
      song: "No song selected",
      about: "Touya. I have been enrolled, un-enrolled, re-enrolled, and I switched my major more than I will admit here. The page is mostly blank on purpose.",
      meet: "People who aren’t going to ask what happened. People who let someone come back at their own pace.",
      interests: { General: "Staying up late, thinking about changing majors, not discussing it.", Music: "Whatever is quiet.", Movies: "I don’t watch much.", Heroes: "I’d rather not." },
      top8: ["shoto", "tomura", "toga", "tokoyami", "jirou", "momo", "izuku", "nejire"],
      blogs: [["06/14", "first post", "I made an account because someone told me the empty page looked suspicious."]],
      comments: [["shoto", "your page is still up."], ["touya", "I know."]]
    },
    {
      id: "iguchi",
      name: "Shuichi Iguchi",
      username: "spinner_",
      initials: "SI",
      theme: "iguchi",
      image: "",
      quote: "your wifi password is on a sticky note. i have seen it.",
      details: ["U.A. University", "Information Systems / Information Technology", "the IT help desk"],
      lastLogin: "09/08/2006",
      mood: "irritated",
      status: "fixing someone else’s printer",
      online: false,
      song: "Basket Case — Green Day",
      about: "Shuichi. I work the IT help desk and I major in IT, so yes, I know what you did. No, I will not fix it for free. Yes, I will fix it for free. It depends on who is asking.",
      meet: "People who read the instructions. People who admit it was their fault.",
      interests: { General: "IT, networking, helping, complaining about being asked to help.", Music: "Pop-punk and whatever the help desk radio plays.", Movies: "Hacker movies, mostly to criticize them.", Heroes: "The guy who taught me to troubleshoot." },
      top8: ["tomura", "jirou", "sero", "kaminari", "patchwork", "hikiishi", "bubaigawara", "izuku"],
      blogs: [["09/06", "Printer", "Turn it off and on again is not an insult. It is a solution."]],
      comments: [["tomura", "your server is slow"], ["iguchi", "your server is slower"]]
    },
    {
      id: "bubaigawara",
      name: "Jin Bubaigawara",
      username: "twice_as_nice",
      initials: "JB",
      theme: "bubaigawara",
      image: "",
      quote: "I’m two guys in one, and both are great",
      details: ["U.A. University", "Business Administration (older / nontraditional student)", "the evening seminar, then the diner"],
      lastLogin: "09/08/2006",
      mood: "thrilled",
      status: "making it up as I go",
      online: true,
      song: "Boulevard of Broken Dreams — Green Day",
      about: "Jin! I returned to college a few years late and I intend to enjoy every minute. I work nights, take classes during the day, and I’m somehow always the loudest one in the room.",
      meet: "Classmates my age. Classmates not my age. Anyone who wants to start a study group at a diner.",
      interests: { General: "Business classes, night shifts, diner coffee, doing three things at once.", Music: "Rock radio.", Movies: "Comedies and heist movies.", Heroes: "Anybody who went back to school after thirty." },
      top8: ["hikiishi", "iguchi", "sako", "mineta", "tomura", "touya", "toga", "izuku"],
      blogs: [["09/05", "Back to school", "Everyone should do this once. Not for the degree. For the humility."]],
      comments: [["mineta", "you’re my mentor now"], ["bubaigawara", "I’m not."]]
    },
    {
      id: "hikiishi",
      name: "Kenji Hikiishi",
      username: "magnetic_kenji",
      initials: "KH",
      theme: "hikiishi",
      image: "",
      quote: "you’ll be drawn to my page. (sorry.)",
      details: ["U.A. University", "Social Work (older / nontraditional student)", "the campus counseling center"],
      lastLogin: "09/07/2006",
      mood: "warm",
      status: "keeping it together",
      online: false,
      song: "Fix You — Coldplay",
      about: "Hello, I’m Kenji. I’m a social-work major and one of the older students here. I joined UltraSpace because someone told me I was missing out. I am not sure what I was missing.",
      meet: "Anyone who needs to talk, or anyone who needs to not talk.",
      interests: { General: "Social work, volunteering, long conversations, good coffee.", Music: "Folk and acoustic.", Movies: "Quiet dramas.", Heroes: "The counselors who showed me what that job is." },
      top8: ["bubaigawara", "iguchi", "sako", "shoji", "touya", "toga", "mirio", "tomura"],
      blogs: [["09/03", "First week", "The hardest part of this program is learning that sometimes the answer is just sitting there with them."]],
      comments: [["bubaigawara", "you’re the best of us"], ["hikiishi", "That’s not a high bar."]]
    },
    {
      id: "sako",
      name: "Atsuhiro Sako",
      username: "centerstage",
      initials: "AS",
      theme: "sako",
      image: "",
      quote: "please hold your applause until the end of my page",
      details: ["U.A. University", "Theatre / Performance", "the black-box theatre"],
      lastLogin: "09/08/2006",
      mood: "dramatic",
      status: "rehearsing",
      online: true,
      song: "Bohemian Rhapsody — Queen",
      about: "Atsuhiro. I study theatre, I perform in everything I can, and I take every audition as an opportunity. If you need a villain, a sidekick, or a scene partner, I’m your guy. If you need a sad monologue, I’m also your guy.",
      meet: "Directors. Casting agents. Anyone who will read the other part.",
      interests: { General: "Theatre, acting, improv, line memorization, post-show food.", Music: "Musicals and show tunes.", Movies: "Anything with a great supporting role.", Heroes: "Every understudy who ever saved a show." },
      top8: ["bubaigawara", "hikiishi", "nejire", "mina", "aoyama", "hagakure", "iguchi", "mirio"],
      blogs: [["09/07", "Auditions", "If you didn’t get the part, you got the experience. That is not a consolation. That is the job."]],
      comments: [["mina", "you were incredible in that scene"], ["sako", "I was merely adequate."]]
    },
    {
      id: "star",
      name: "Star",
      username: "starlight",
      initials: "S",
      theme: "star",
      image: "",
      quote: "I’m not quiet, I’m selective.",
      details: ["U.A. University", "Nursing", "nursing lab / clinical placements"],
      lastLogin: "09/07/2006",
      mood: "calm",
      status: "studying for an anatomy exam",
      online: false,
      song: "Breathe (2 AM) — Anna Nalick",
      about: "I’m Star. I study nursing. I talk to about three people regularly, and I like it that way. If we are in the same class, there is a decent chance I already think you are interesting.",
      meet: "People who are honest. People who know what they’re doing. Anyone who brings snacks to a study session.",
      interests: { General: "Nursing, anatomy flashcards, quiet places, a small number of good friends.", Music: "Whatever Jirou makes me.", Movies: "Medical dramas I can critique.", Heroes: "The nurses who trained me." },
      top8: ["mina", "jirou", "patchwork", "tsuyu", "shoji", "momo", "izuku", "toga"],
      blogs: [["09/05", "Clinical hours", "Today I learned the difference between being quiet and being absent. Most people can’t tell."]],
      comments: [["mina", "you’re too good for this exam"], ["star", "I haven’t taken it yet"], ["jirou", "you’ll pass"]]
    }
  ],

  relationships: [
    { a: "patchwork", b: "tamaki", type: "romance", direction: "mutual", secret: true, reality: "secretly dating", rumor: "barely know each other", note: "Quiet devotion; Mirio and Nejire know." },
    { a: "kirishima", b: "bakugo", type: "romance", direction: "a-to-b", timeline: [
      { stage: "Early", text: "Kirishima knows he has a crush and tells friends. He reads every sign as possibly about him. Bakugo thinks of him as an unusually important friend." },
      { stage: "Middle", text: "Bakugo starts prioritizing Kirishima: his schedule, his absence, his reactions, and a one-person Top 8. All of it gets filed under friendship. Kirishima, tired of overanalyzing, trains himself not to assume." },
      { stage: "Later", text: "Bakugo’s choices (songs, photos, layout details) start being romantic without his saying so. Kirishima stops trusting the signs just as they become real." },
      { stage: "Eventually", text: "Bakugo realizes Kirishima has been in a separate category for a while." }
    ], reality: "Kirishima’s crush; Bakugo developing without noticing", rumor: "best friends", note: "Kirishima knows he likes Bakugo and has told friends, but keeps trying not to read into the evidence because he doesn’t want it to be wishful thinking. Bakugo starts out seeing Kirishima as a particularly important friend and never interrogates it. Then it gets specific: he knows his schedule, notices when he’s missing, saves him a seat, picks songs, photos and layout details with Kirishima in mind, and has made him the only person in his Top 8. Kirishima falls first, but Bakugo has been building the relationship without realizing it. When he finally does, it is “Oh,” then “Oh, fuck.”" },
    { a: "shoto", b: "izuku", type: "romance", direction: "a-to-b", timeline: [
      { stage: "Early", text: "Shoto realizes first and keeps choosing Izuku across unrelated schedules and routines." },
      { stage: "Later", text: "Izuku takes a long time to understand his own pattern." }
    ], reality: "Shoto knows; Izuku catches up late", rumor: "very important friends", note: "The profile evidence is not subtle." },
    { a: "toga", b: "ochaco", type: "romance", direction: "mutual", reality: "mutual love; unsustainable", rumor: "dangerous attachment", note: "Genuine does not automatically mean safe." },
    { a: "momo", b: "jirou", type: "romance", direction: "mutual", reality: "mutual interest; unresolved", rumor: "close friendship", note: "Part of Momo’s bisexual realization. Jirou likes both Momo and Kaminari." },
    { a: "jirou", b: "kaminari", type: "romance", direction: "mutual", reality: "mutual attraction; unresolved", rumor: "obvious chemistry", note: "Attraction is not an obligation. Jirou likes both Kaminari and Momo." },
    { a: "momo", b: "shoto", type: "former", direction: "mutual", reality: "exes → friends", rumor: "might get back together", note: "The romantic pilot program ended successfully." },
    { a: "patchwork", b: "izuku", type: "platonic", direction: "mutual", reality: "bffs; day-one homie; flirty but platonic", rumor: "something is definitely happening", note: "Aaliyah is naturally flirty and their fake-dating history makes the rumors worse. Flirting is not romance." },
    { a: "patchwork", b: "jirou", type: "platonic", direction: "mutual", reality: "freshman roommates / bffs", rumor: "known close friendship", note: "Jirou was the first person Aaliyah met at college. Jirou knows Aaliyah has someone." },
    { a: "patchwork", b: "ochaco", type: "platonic", direction: "mutual", reality: "bffs; part of the original core group", rumor: "close friends", note: "Trusted circle." },
    { a: "kaminari", b: "sero", type: "platonic", direction: "mutual", reality: "platonic soulmates", rumor: "best friends", note: "Zero romance. The chart will not lie." },
    { a: "tamaki", b: "mirio", type: "platonic", direction: "mutual", reality: "Big Three / found family", rumor: "best friends", note: "Mirio knows the secret." },
    { a: "tamaki", b: "nejire", type: "platonic", direction: "mutual", reality: "Big Three / found family", rumor: "best friends", note: "Nejire knows the secret." },
    { a: "mirio", b: "nejire", type: "platonic", direction: "mutual", reality: "Big Three / found family", rumor: "best friends", note: "Durable three-person friendship." },
    { a: "patchwork", b: "tomura", type: "friction", kind: "mutual dislike; begrudging respect", direction: "mutual", reality: "academic rivals / mutual irritation", rumor: "arguing in the lab again", note: "Competence respect is not friendship." },
    { a: "patchwork", b: "iida", type: "platonic", direction: "mutual", reality: "bffs; intellectual friendship", rumor: "arguing about policy again", note: "Policy, ethics, systems, arguments. He keeps trying to recruit her to student government. She helps a lot, then vanishes, then says maybe, sometimes." },
    { a: "patchwork", b: "mina", type: "platonic", direction: "mutual", reality: "bffs", rumor: "always out together", note: "Fashion nonsense and social outings. Aaliyah introduced Mina to her girlfriend." },
    { a: "patchwork", b: "tsuyu", type: "platonic", direction: "mutual", reality: "friends", rumor: "blunt-person solidarity", note: "Mutual reality-checking." },
    { a: "patchwork", b: "momo", type: "platonic", direction: "mutual", reality: "friends", rumor: "intelligent-girl solidarity", note: "Smart-girl solidarity plus fashion, money and magazine nonsense." },
    { a: "patchwork", b: "sero", type: "platonic", direction: "mutual", reality: "philosophy / yapping friends", rumor: "known friendship", note: "Exploratory, weird hypotheticals." },
    { a: "patchwork", b: "tokoyami", type: "platonic", direction: "mutual", reality: "philosophy-table friends", rumor: "known friendship", note: "He genuinely enjoys the discussions." },
    { a: "patchwork", b: "mirio", type: "platonic", direction: "mutual", reality: "honorary fourth of the Big Three", rumor: "known friendship", note: "Mirio knows the secret." },
    { a: "patchwork", b: "nejire", type: "platonic", direction: "mutual", reality: "honorary fourth of the Big Three", rumor: "known friendship", note: "Nejire knows the secret." },
    { a: "patchwork", b: "hagakure", type: "platonic", direction: "mutual", reality: "close friends", rumor: "known friendship", note: "Loves hanging out with Toru. Toru is always included, and Toru hears everything." },
    { a: "izuku", b: "iida", type: "platonic", direction: "mutual", reality: "original core friend group", rumor: "known friendship", note: "Izuku, Iida and Ochaco are the original trio, and Aaliyah is part of it too." },
    { a: "iida", b: "ochaco", type: "platonic", direction: "mutual", reality: "original core friend group", rumor: "known friendship", note: "Izuku, Iida and Ochaco are the original trio, and Aaliyah is part of it too." },
    { a: "izuku", b: "ochaco", type: "platonic", direction: "mutual", reality: "original core friend group", rumor: "known friendship", note: "Izuku, Iida and Ochaco are the original trio, and Aaliyah is part of it too." },
    { a: "tamaki", b: "tsuyu", type: "platonic", direction: "mutual", reality: "academic / environmental overlap", rumor: "barely know each other", note: "Quietly familiar through the environmental-science side of campus." },
    { a: "tokoyami", b: "jirou", type: "platonic", direction: "mutual", reality: "alt / music affinity", rumor: "known friendship", note: "Shared taste, comfortable company." },
    { a: "tokoyami", b: "tamaki", type: "platonic", direction: "mutual", reality: "“Department of Darkness”", rumor: "known friendship", note: "Quieter personalities. Comfortable coexistence. Tokoyami considers Amajiki a person of discernment." },
    { a: "hagakure", b: "mina", type: "platonic", direction: "mutual", reality: "close friends", rumor: "known friendship", note: "Mina never forgets to include her." },
    { a: "hagakure", b: "jirou", type: "platonic", direction: "mutual", reality: "girls’ social orbit", rumor: "known friendship", note: "Part of the broader girls’ circle." },
    { a: "mina", b: "jirou", type: "platonic", direction: "mutual", reality: "freshman-girl cluster", rumor: "known friendship", note: "Recurring close cluster with Aaliyah." },
    { a: "tomura", b: "iguchi", type: "platonic", direction: "mutual", reality: "loyalty / belonging", rumor: "known friendship", note: "Spinner will follow him farther than good judgment allows." },
    { a: "touya", b: "shoto", type: "friction", kind: "estranged / bad history", direction: "mutual", reality: "estranged siblings", rumor: "people only half-know", note: "Family history explains the context. It does not entitle Touya to Shoto’s forgiveness or access." },
    { a: "ojiro", b: "hagakure", type: "platonic", direction: "mutual", reality: "very close friends (for now)", rumor: "everyone assumes they’re dating", note: "Genuinely just friends, and really cute about it." },
    { a: "tokoyami", b: "ojiro", type: "platonic", direction: "mutual", reality: "close friends", rumor: "known friendship", note: "Part of Tokoyami’s friend group." },
    { a: "tokoyami", b: "shoji", type: "platonic", direction: "mutual", reality: "close friends", rumor: "known friendship", note: "Part of Tokoyami’s friend group." },
    { a: "tokoyami", b: "koda", type: "platonic", direction: "mutual", reality: "close friends", rumor: "known friendship", note: "Part of Tokoyami’s friend group." },
    { a: "tokoyami", b: "sato", type: "platonic", direction: "mutual", reality: "close friends", rumor: "known friendship", note: "Part of Tokoyami’s friend group." },
    { a: "tokoyami", b: "aoyama", type: "platonic", direction: "mutual", reality: "close friends", rumor: "known friendship", note: "Part of Tokoyami’s friend group." },
    { a: "mineta", b: "kaminari", type: "platonic", direction: "mutual", reality: "close friend group", rumor: "known friendship", note: "Silly fellas." },
    { a: "mineta", b: "sero", type: "platonic", direction: "mutual", reality: "close friend group", rumor: "known friendship", note: "Silly fellas." },
    { a: "patchwork", b: "bakugo", type: "platonic", direction: "mutual", reality: "cool, chill friends", rumor: "constantly bickering", note: "They bicker (key word: bicker) but respect each other. He stands up for her, she stands up for him, and she teases him a lot." },
    { a: "patchwork", b: "shoto", type: "platonic", direction: "mutual", reality: "friends", rumor: "known friendship", note: "Part of the “annoyingly expensive” trio with Momo." },
    { a: "mina", b: "star", type: "romance", direction: "mutual", reality: "dating", rumor: "close friends", note: "Established relationship. Aaliyah introduced them." },
    { a: "patchwork", b: "star", type: "platonic", direction: "mutual", reality: "friends", rumor: "known friendship", note: "Star mostly talks to Aaliyah, Jirou and Mina. Aaliyah introduced her to Mina." },
    { a: "jirou", b: "star", type: "platonic", direction: "mutual", reality: "friends", rumor: "known friendship", note: "Star mostly talks to Jirou, Aaliyah and Mina." },
    { a: "toga", b: "star", type: "platonic", direction: "mutual", reality: "nursing-class acquaintances", rumor: "barely know each other", note: "Star would know Toga from nursing and think “interesting girl.”" },
    { a: "mina", b: "kirishima", type: "platonic", direction: "mutual", reality: "best friends", rumor: "best friends", note: "Genuinely very close, not just two people in the same wider friend group. One of each other’s major platonic relationships." },
    { a: "kirishima", b: "kaminari", type: "platonic", direction: "mutual", reality: "close friends", rumor: "known friendship", note: "A real friendship, not just membership in the same social cluster." },
    { a: "kirishima", b: "sero", type: "platonic", direction: "mutual", reality: "close friends", rumor: "known friendship", note: "A real friendship, not just membership in the same social cluster." },
    { a: "tamaki", b: "kirishima", type: "platonic", direction: "mutual", reality: "friends through Fat Gum’s restaurant", rumor: "barely know each other", note: "Tamaki was already established at Fat Gum’s and helps Kirishima find his footing there." },
    { a: "bakugo", b: "kaminari", type: "platonic", direction: "mutual", reality: "friends Bakugo keeps around on purpose", rumor: "known friendship", note: "Bakugo chooses to keep him around, which says more than he would admit." },
    { a: "bakugo", b: "sero", type: "platonic", direction: "mutual", reality: "friends Bakugo keeps around on purpose", rumor: "known friendship", note: "Bakugo chooses to keep him around, which says more than he would admit." },
    { a: "bakugo", b: "izuku", type: "former", kind: "childhood history", direction: "mutual", reality: "childhood history", rumor: "everybody knows there is history", note: "Their shared childhood shapes both of them. The exact history is still to be defined." },
    { a: "bakugo", b: "shoto", type: "platonic", kind: "rivalry", direction: "mutual", reality: "rivalry / competitive friendship", rumor: "known friendship", note: "Competitive in a way that is closer to respect than dislike." },
    { a: "ochaco", b: "tsuyu", type: "platonic", direction: "mutual", reality: "close friends", rumor: "known friendship", note: "An important close friendship." },
    { a: "momo", b: "iida", type: "platonic", direction: "mutual", reality: "academic / student-governance overlap", rumor: "known friendship", note: "Two serious people who take the job seriously." },
    { a: "aoyama", b: "mina", type: "platonic", direction: "mutual", reality: "fashion overlap", rumor: "known friendship", note: "Fashion Design meets Fashion Merchandising." },
    { a: "aoyama", b: "patchwork", type: "platonic", direction: "mutual", reality: "fashion friends", rumor: "known friendship", note: "Fashion-related interactions and taste debates." },
    { a: "sato", b: "hagakure", type: "platonic", direction: "mutual", reality: "hospitality / events overlap", rumor: "known friendship", note: "Culinary Arts and Event Management naturally overlap." },
    { a: "koda", b: "tsuyu", type: "platonic", direction: "mutual", reality: "ecology / biology overlap", rumor: "known friendship", note: "Wildlife biology meets aquatic ecology." },
    { a: "koda", b: "tamaki", type: "platonic", direction: "mutual", reality: "ecology / biology overlap", rumor: "known friendship", note: "Connected through the biology and ecology side of campus." },
    { a: "ojiro", b: "kirishima", type: "platonic", direction: "mutual", reality: "sports / exercise overlap", rumor: "known friendship", note: "Sports management with a fitness-science crowd." },
    { a: "ojiro", b: "izuku", type: "platonic", direction: "mutual", reality: "sports / exercise overlap", rumor: "known friendship", note: "Sports management with a fitness-science crowd." },
    { a: "shoji", b: "koda", type: "platonic", direction: "mutual", reality: "friends in Tokoyami’s group", rumor: "known friendship", note: "Two gentle, observant people in the same circle." },
    { a: "ojiro", b: "sato", type: "platonic", direction: "mutual", reality: "friends in Tokoyami’s group", rumor: "known friendship", note: "Training and cooking tend to end up at the same table." },
    { a: "shoji", b: "toga", type: "platonic", direction: "mutual", reality: "early nursing-class overlap", rumor: "barely know each other", note: "Overlap before Toga changes majors." },
    { a: "toga", b: "bubaigawara", type: "platonic", direction: "mutual", reality: "warm, protective friends", rumor: "known friendship", note: "Jin is affectionate with her. That loyalty can also make him complicit." },
    { a: "bubaigawara", b: "hikiishi", type: "platonic", direction: "mutual", reality: "older-student friendship", rumor: "known friendship", note: "Two nontraditional students. Kenji is the more grounded one without being the designated Good One." },
    { a: "bubaigawara", b: "iguchi", type: "platonic", direction: "mutual", reality: "loyal friends", rumor: "known friendship", note: "Jin’s warmth and Spinner’s loyalty make it easy to follow Tomura’s worse ideas." },
    { a: "sako", b: "bubaigawara", type: "platonic", direction: "mutual", reality: "theatrical friends", rumor: "known friendship", note: "Both are good at making a bad idea sound fun." },
    { a: "hikiishi", b: "toga", type: "platonic", direction: "mutual", reality: "caring but cautious", rumor: "known friendship", note: "Kenji sees what Toga is going through and says so, which she does not always love." },
    { a: "tomura", b: "touya", type: "friction", kind: "uneasy alliance", direction: "mutual", reality: "uneasy alliance", rumor: "people avoid them both", note: "They understand each other’s worst habits and don’t pretend to be friends." }
  ],

  circles: [
    { name: "Bakusquad", kind: "friend group", members: ["bakugo","kirishima","kaminari","sero","mina"], floaters: ["patchwork"], note: "Aaliyah is part of the squad too, but she floats in and out of it." },
    { name: "Dekusquad", kind: "friend group", members: ["izuku","ochaco","iida","tsuyu","shoto","momo","patchwork"], note: "Aaliyah is part of the squad (through the original core group) and also floats between squads." },
    { name: "Accidental philosophy club", kind: "friend group", members: ["iida","sero","patchwork","tokoyami"], note: "Nobody founded it. It just happens at the same table." },
    { name: "Bandmates", kind: "band", members: ["jirou","kaminari","bakugo","momo"], note: "Music is the shared thread." },
    { name: "The girls", kind: "friend group", members: ["patchwork","jirou","mina","hagakure"], note: "Matching things pile up over college: bracelets, phone charms, photo-booth strips, burned CDs. Toru always gets hers, even when she isn’t there. Nobody forgets her. They only forget she’s in the room." },
    { name: "Original core group", kind: "friend group", members: ["izuku","iida","ochaco","patchwork"], note: "Izuku, Iida and Ochaco are the original trio, and Aaliyah is part of it too. This is the closest part of the Dekusquad." },
    { name: "Big Three (+ honorary fourth)", kind: "found family", members: ["tamaki","mirio","nejire","patchwork"], note: "Aaliyah is the honorary fourth. Mirio and Nejire are also the only peers who know about Aaliyah and Tamaki." },
    { name: "The League", kind: "found family", members: ["tomura","toga","iguchi","touya","bubaigawara","hikiishi","sako"], note: "Found family and mutual enabling. They care about one another and sometimes reinforce each other’s worst impulses. Jin is warm and loyal, which can pull him into bad decisions. Kenji is the more grounded one without being the designated Good One. Atsuhiro is charming and theatrical but still morally messy." },
    { name: "Main friend network ↔ the League", kind: "social category", members: [], note: "Generally distrustful or antagonistic overlap, because these people have earned bad reputations. Individual relationships can differ." },
    { name: "Tokoyami’s friend group (name TBD)", kind: "friend group", members: ["tokoyami","ojiro","shoji","koda","sato","aoyama"], note: "Close friends, and Tokoyami is part of it." },
    { name: "Mineta / Kaminari / Sero", kind: "friend group", members: ["mineta","kaminari","sero"], note: "Silly fellas." },
    { name: "The expensive kids", kind: "friend group", members: ["shoto","patchwork","momo"], note: "They sit on Momo’s bed with a magazine, go yay or nay on every page, and then decide whether to buy it." },
    { name: "Music corner", kind: "friend group", members: ["jirou","tokoyami","tamaki"], note: "Overlapping taste without identical taste. Tamaki quietly knows way more than anyone expected." },
    { name: "Student governance", kind: "organization", members: ["iida","momo"], floaters: ["patchwork","bakugo"], note: "Iida and Momo both really want Aaliyah to join. She helps a lot, then vanishes. They also want Bakugo, who would be a really good enforcer." }
  ],

  articles: [
    {
      id: "aizawa-directory",
      category: "FACULTY DIRECTORY",
      headline: "Shota Aizawa — Faculty Record",
      deck: "Office hours remain technically available. Appointment strongly recommended.",
      byline: "U.A. UNIVERSITY OFFICE OF ACADEMIC AFFAIRS",
      date: "Updated Fall 2006",
      initials: "SA",
      body: [
        "Professor Shota Aizawa teaches advanced seminars at U.A. University and serves as a faculty adviser. His official biography is four sentences long. Attempts to expand it have been declined.",
        "Students are asked to review the syllabus before sending questions already answered by the syllabus. The department has confirmed that this sentence was specifically requested for inclusion.",
        "Professor Aizawa does not maintain an UltraSpace profile. Several accounts using his name have been reported and removed."
      ]
    },
    {
      id: "present-mic-radio",
      category: "CAMPUS LIFE",
      headline: "Present Mic expands late-night campus radio programming",
      deck: "The new schedule promises interviews, student bands, and a volume level the library has already objected to.",
      byline: "U.A. STUDENT NEWSWIRE",
      date: "September 5, 2006",
      initials: "PM",
      body: [
        "Professor Hizashi Yamada announced an expanded fall schedule for the campus radio station this week, including a new student-music hour and a recurring interview segment.",
        "Yamada described the programming as a chance for the campus to hear voices that might otherwise remain in dorm rooms, practice spaces, or extremely customized UltraSpace profiles.",
        "The station begins broadcasting at eight. Complaints about volume may be directed to a form nobody expects him to read quietly."
      ]
    },
    {
      id: "all-might-lecture",
      category: "CAMPUS NEWS",
      headline: "All Might lecture fills auditorium beyond capacity",
      deck: "Overflow viewing rooms opened after students began lining up before sunrise.",
      byline: "U.A. STUDENT NEWSWIRE",
      date: "September 1, 2006",
      initials: "AM",
      body: [
        "Visiting lecturer Toshinori Yagi drew a capacity audience for the university’s opening leadership forum, with additional seating redirected to two nearby halls.",
        "The talk focused on responsibility, public identity, and the difference between appearing fearless and choosing to act while afraid.",
        "A recording will be placed in the campus archive after captions are completed. Students have been asked to stop requesting the raw file through UltraSpace messages."
      ]
    }
  ]
};
